### ISSUE TITLE
crontab grafana_alerts

### ISSUE THREAD

**Issue by systems1** [pabloa/grafana-alerts#12]
which  python script should be  added  in crontab 
I only see grafana_alerts module and no grafana_alerts.py as per documentation crontab 

"Add a cron task to execute grafana_alerts for example each 3 minutes::
*/3 \* \* \* \*     grafana_alerts"

Red Hat Enterprise Linux Server release 6.6
/usr/lib/python2.6/site-packages/grafana_alerts>]ls -l
total 80
-rw-r--r-- 1 root root 11075 Oct 28 16:29 alerting.py
-rw-r--r-- 1 root root  9742 Oct 28 16:29 alerting.pyc
-rw-r--r-- 1 root root  1130 Oct 28 16:29 html_version_item.html
-rw-r--r-- 1 root root  2801 Oct 28 16:29 html_version_main.html
-rw-r--r-- 1 root root   315 Oct 28 16:29 **init**.py
-rw-r--r-- 1 root root   620 Oct 28 16:29 **init**.pyc
-rw-r--r-- 1 root root  1436 Oct 28 16:29 launcher.py
-rw-r--r-- 1 root root  2375 Oct 28 16:29 launcher.pyc
-rw-r--r-- 1 root root     9 Oct 28 16:29 package_data.dat
-rw-r--r-- 1 root root 15718 Oct 28 16:29 reporting.py
-rw-r--r-- 1 root root 11095 Oct 28 16:29 reporting.pyc

**Comment by vmironenko** [comment]
/usr/bin/grafanaalerts

**Comment by systems1** [comment]
thanks for file location 
I see its grafanaAlerts 
when I run it i get below errors ,could be my installation packages dependancies 

/usr/bin/grafanaAlerts
Traceback (most recent call last):
  File "/usr/bin/grafanaAlerts", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: jmespath>=0.6.1

**Comment by vmironenko** [comment]
Hi

You need to install jmespath ( >=0.6.1 ):

# pip install jmespath

2015-11-05 3:56 GMT+06:00 systems1 notifications@github.com:

**Comment by PodioSpaz** [comment]
I'm having the same error `pkg_resources.DistributionNotFound: jmespath>=0.6.1`

jmespath is installed.

## pip show jmespath

Metadata-Version: 2.0
Name: jmespath
Version: 0.9.0
Summary: JSON Matching Expressions
Home-page: https://github.com/jmespath/jmespath.py
Author: James Saryerwinnie
Author-email: 
License: UNKNOWN
Location: /usr/lib/python2.6/site-packages
Requires:

**Comment by iferrarims** [comment]
@PodioSpaz I met the same error. By reinstall jmespath, everything is fine. 
`pip install jmespath==0.6.1  --force-reinstall`
