### ISSUE TITLE
httplib.InvalidURL

### ISSUE THREAD

**Issue by eyaqub** [pabloa/grafana-alerts#15]
Hi, I am trying to setup grafana_alerts module. I installed python and grafana_alerts module in my docker container. After tagging the dashboard with "monitored" and adjusting the config file at /etc/grafana_alerts, I restarted containers. Running the grafanaAlerts command in the container gives a sort of error message: "httplib.InvalidURL: nonnumeric port: '3130api'"
$ grafanaAlerts  
Traceback (most recent call last):
  File "/usr/local/bin/grafanaAlerts", line 9, in <module>
    load_entry_point('grafana-alerts==1.0.0.dev7', 'console_scripts', 'grafanaAlerts')()
  File "/usr/local/lib/python2.7/dist-packages/grafana_alerts/**init**.py", line 12, in main
    return the_launcher.launch()
  File "/usr/local/lib/python2.7/dist-packages/grafana_alerts/launcher.py", line 16, in launch
    alert_checker.check()
  File "/usr/local/lib/python2.7/dist-packages/grafana_alerts/alerting.py", line 38, in check
    dashboard_data_list = scanner.obtain_dashboards()
  File "/usr/local/lib/python2.7/dist-packages/grafana_alerts/alerting.py", line 157, in obtain_dashboards
    contents = urllib2.urlopen(request).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1166, in do_open
    h = http_class(host, timeout=req.timeout, *_http_conn_args)
  File "/usr/lib/python2.7/httplib.py", line 712, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/usr/lib/python2.7/httplib.py", line 754, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
httplib.InvalidURL: nonnumeric port: '3130api'

Any hints what might be going on here and where to fix the nonnumeric mention of port?
Thanks.

**Comment by vayxdev** [comment]
@eyaqub The URL where grafana server is listening. It must finish with the character '/' (default value: http://localhost:3130)
